export interface ArticleSection {
  heading: string;
  body: string;
  bullets?: string[];
}

export interface Article {
  slug: string;
  title: string;
  date: string;
  tag: string;
  readTime: string;
  img: string;
  excerpt: string;
  intro: string;
  sections: ArticleSection[];
  conclusion: string;
}

export const ARTICLES: Article[] = [
  {
    slug: "solar-inverter-guide",
    title: "How to Choose the Right Solar Inverter for Your Home",
    date: "12 June 2025",
    tag: "Buying Guide",
    readTime: "6 min read",
    img: "https://images.unsplash.com/photo-1780445392484-38a4852a1fd8?w=1200&h=600&fit=crop&auto=format",
    excerpt: "Selecting the right inverter is critical to the performance of your solar system. We break down the key types and what to look for.",
    intro: "The inverter is the brain of your solar system — it converts the DC electricity generated by your solar panels into the AC electricity your home appliances use. Choosing the wrong inverter can mean poor performance, wasted energy and expensive replacements down the line. This guide walks you through everything you need to know to make the right choice for your Kenyan home or business.",
    sections: [
      {
        heading: "The Three Main Types of Solar Inverters",
        body: "Before choosing an inverter, it is important to understand the three main categories available in the Kenyan market:",
        bullets: [
          "String Inverters — The most affordable option. All solar panels connect to one central inverter. Best for rooftops with no shading and panels facing the same direction.",
          "Hybrid Inverters — Connect to both solar panels and a battery bank. They can operate on-grid, off-grid or both simultaneously. Ideal for Kenyan homes that want backup power during outages.",
          "Off-Grid Inverters — Designed for locations with no grid connection. Paired with a battery bank and charge controller to create a fully independent power system.",
        ],
      },
      {
        heading: "Key Specifications to Compare",
        body: "When evaluating inverters, focus on these core technical specifications:",
        bullets: [
          "Continuous Power Rating (VA or kW) — Must match or exceed your total connected load. Undersize and your inverter will overload; oversize and you waste money.",
          "Battery Voltage (12V, 24V or 48V) — Larger systems should use 48V systems for greater efficiency and lower cable losses.",
          "Surge Capacity — Some appliances like refrigerators and pumps draw 3–6× their rated power at startup. Your inverter needs enough surge capacity to handle this.",
          "Efficiency Rating — Look for inverters with ≥93% efficiency. Every percentage point of inefficiency translates to wasted electricity and heat.",
          "MPPT Charge Controller — For hybrid and off-grid systems, ensure the built-in charge controller uses MPPT technology for maximum energy harvest from your panels.",
        ],
      },
      {
        heading: "Pure Sine Wave vs Modified Sine Wave",
        body: "Always choose a pure sine wave inverter for a home solar system. Modified sine wave inverters are cheaper but can damage sensitive electronics including LED TVs, laptop chargers, refrigerators and medical equipment. All reputable brands supplied by Pekims Technologies — including SUOER and HOBER — produce pure sine wave output as standard.",
      },
      {
        heading: "Recommended Inverter Sizes for Kenyan Homes",
        body: "As a general guide, here is what different property types typically require:",
        bullets: [
          "Small home (1–2 bedrooms, basic appliances): 1–2 kVA hybrid inverter",
          "Medium home (3 bedrooms, TV, fridge, fans): 3–5 kVA hybrid inverter",
          "Large home or small business: 5–10 kVA hybrid inverter",
          "Commercial or industrial premises: 10–20 kVA or multiple units in parallel",
        ],
      },
      {
        heading: "Important Features to Look For",
        body: "Beyond the basic specs, the following features significantly improve the experience of owning a solar system:",
        bullets: [
          "LCD or LED display showing battery level, load, input voltage and fault codes",
          "Remote monitoring via smartphone app or web portal",
          "Automatic transfer switch (ATS) for seamless switching between solar, battery and grid",
          "Overload, short-circuit and over-temperature protection",
          "Generator input compatibility for hybrid backup",
        ],
      },
    ],
    conclusion: "Choosing the right inverter is one of the most important decisions in designing your solar system. At Pekims Technologies, our engineers conduct a detailed load analysis before recommending any inverter — ensuring you get a system that matches your actual energy needs, not just a generic off-the-shelf solution. Contact us today for a free consultation and system recommendation.",
  },

  {
    slug: "solar-water-pumping-guide",
    title: "Solar Water Pumping: A Complete Guide for Kenyan Farmers",
    date: "28 May 2025",
    tag: "Agricultural",
    readTime: "10 min read",
    img: "https://images.unsplash.com/photo-1764697761858-e126b8c7aaa6?w=1200&h=600&fit=crop&auto=format",
    excerpt: "Everything you need to know about sizing, installing and maintaining a solar water pump for irrigation or livestock water supply.",
    intro: "For Kenyan farmers, reliable water access is the difference between a productive harvest and a failed season. Diesel-powered pumps are expensive to run, require constant fuel supply and break down frequently. Solar water pumps offer a clean, low-maintenance alternative that pays for itself within 2–3 seasons. This guide explains how solar pumps work, how to size one correctly and what to expect from a Pekims Technologies installation.",
    sections: [
      {
        heading: "How Solar Water Pumps Work",
        body: "A solar water pumping system consists of three main components: solar panels that generate DC electricity, a pump controller that regulates the motor speed based on available sunlight, and a submersible or surface pump that moves the water. The system pumps water during daylight hours directly into an elevated storage tank. From the tank, gravity feeds water to irrigation points, troughs or taps — meaning you get water delivery even after sunset at no extra cost.",
      },
      {
        heading: "Submersible vs Surface Pumps",
        body: "The type of pump you need depends on your water source:",
        bullets: [
          "Submersible pumps — Installed inside a borehole or deep well. Best for depths of 10–300 metres. Highly efficient and protected from weather.",
          "Surface pumps — Installed above ground and draw water from rivers, dams or shallow wells (less than 8 metres deep). Easier to maintain but exposed to environmental conditions.",
          "Floating pumps — Placed directly on open water surfaces like dams or ponds. Ideal for irrigation from seasonal water bodies.",
        ],
      },
      {
        heading: "How to Size Your Solar Pump System",
        body: "Correct sizing is critical. An undersized system will not meet your water needs; an oversized system wastes capital. Here are the key factors our engineers assess:",
        bullets: [
          "Daily water demand — How many litres per day do you need? (Crop irrigation, livestock, household use)",
          "Total Dynamic Head (TDH) — The vertical distance the water must be lifted plus friction losses in pipes",
          "Borehole yield — The maximum sustainable pumping rate of your water source",
          "Solar resource — Kenya averages 5–6 peak sun hours per day, which determines how long the pump runs",
          "Tank storage — How much reserve you need for cloudy days or periods of high demand",
        ],
      },
      {
        heading: "Real-World Water Output Examples",
        body: "To give you a sense of what different system sizes can achieve in Kenya:",
        bullets: [
          "1 HP (0.75 kW) system: ~20,000 L/day from 30m depth — suitable for 2–3 acres of drip irrigation",
          "3 HP (2.2 kW) system: ~50,000 L/day from 50m depth — suitable for 8–10 acres or a medium dairy farm",
          "5 HP (3.7 kW) system: ~80,000 L/day from 80m depth — suitable for large-scale irrigation or community supply",
          "10 HP (7.5 kW) system: ~150,000 L/day from 100m depth — commercial farming or institutional supply",
        ],
      },
      {
        heading: "Maintenance Requirements",
        body: "One of the biggest advantages of solar pumps is minimal maintenance. A well-installed system from Pekims Technologies will require:",
        bullets: [
          "Monthly: Clean solar panels with a damp cloth to remove dust (major cause of energy loss in Kenya)",
          "Quarterly: Inspect cable connections and controller for signs of corrosion or damage",
          "Annual: Check pump mechanical seals and motor bearings; inspect borehole casing if applicable",
          "As needed: Replace pump controller display or sensors if faults occur",
        ],
      },
      {
        heading: "Cost and Return on Investment",
        body: "A solar water pumping system eliminates diesel costs immediately. A typical 3 HP diesel pump consumes 15–20 litres of fuel per day, costing KES 2,000–3,000 daily. A solar equivalent with zero fuel cost pays back in 18–30 months and then operates essentially free for 20+ years.",
      },
    ],
    conclusion: "Solar water pumping is one of the highest-return investments available to Kenyan farmers today. Pekims Technologies has installed over 120 pumping systems across the country, from small homestead borehole pumps to large-scale commercial irrigation systems. Contact us for a free site assessment and we will design a system matched precisely to your farm's water needs.",
  },

  {
    slug: "lithium-vs-lead-acid-batteries",
    title: "Understanding Lithium vs Lead-Acid Solar Batteries",
    date: "10 May 2025",
    tag: "Technology",
    readTime: "8 min read",
    img: "https://images.unsplash.com/photo-1619641805634-b867f535071c?w=1200&h=600&fit=crop&auto=format",
    excerpt: "A side-by-side comparison of the two main battery technologies used in solar storage systems, with advice on which is right for you.",
    intro: "Battery storage is the component that determines how long your solar system can power your home after the sun goes down. In the Kenyan market, two technologies dominate: traditional lead-acid batteries and modern lithium iron phosphate (LiFePO4) batteries. Each has a distinct profile of performance, cost and maintenance requirements. This article gives you an honest comparison to help you make the right decision.",
    sections: [
      {
        heading: "How Lead-Acid Batteries Work",
        body: "Lead-acid batteries have been used in solar systems for decades. They use a chemical reaction between lead plates and sulphuric acid electrolyte to store and release energy. The two main variants available in Kenya are Flooded Lead-Acid (FLA), which require regular water top-ups, and Sealed AGM or Gel batteries, which are maintenance-free but more expensive. They are heavy, bulky and sensitive to deep discharge — consistently discharging below 50% significantly shortens their lifespan.",
      },
      {
        heading: "How Lithium Iron Phosphate (LiFePO4) Batteries Work",
        body: "LiFePO4 batteries use lithium ions moving between electrodes to store energy. They are fundamentally more efficient, more compact and far more tolerant of deep discharge than lead-acid alternatives. Unlike other lithium chemistries (such as lithium cobalt oxide used in phone batteries), LiFePO4 is thermally stable and does not pose a fire risk — making it safe for home and commercial installation.",
      },
      {
        heading: "Head-to-Head Comparison",
        body: "Here is how the two technologies compare across the metrics that matter most for Kenyan solar users:",
        bullets: [
          "Usable Capacity — Lead-acid: 50% of rated capacity. Lithium: 80–95% of rated capacity. A 200Ah lead-acid gives you 100Ah usable; a 200Ah lithium gives you 160–190Ah usable.",
          "Cycle Life — Lead-acid: 300–600 cycles. LiFePO4: 3,000–6,000 cycles. Lithium lasts 5–8× longer.",
          "Efficiency — Lead-acid: 75–85% round-trip. LiFePO4: 95–98% round-trip. Less energy wasted as heat.",
          "Weight — A 200Ah lead-acid battery weighs 55–65 kg. A 200Ah lithium weighs 20–25 kg.",
          "Maintenance — Lead-acid (FLA): monthly water checks required. Lithium: completely maintenance-free.",
          "Temperature Performance — Lead-acid loses significant capacity in cold weather. Lithium performs far better across the temperature range of 0–45°C typical in Kenya.",
          "Upfront Cost — Lead-acid is cheaper to buy initially (KES 15,000–25,000 per 200Ah unit). Lithium costs more upfront (KES 45,000–80,000 per 200Ah unit).",
          "Lifetime Cost — Despite higher upfront cost, lithium is typically cheaper over 10 years because it lasts 5–8× longer and requires no maintenance.",
        ],
      },
      {
        heading: "Which Is Right for You?",
        body: "Choose lead-acid if your budget is tight and you are comfortable with regular maintenance. Choose lithium if you want maximum performance, minimal maintenance and the lowest long-term cost. For commercial and agricultural installations where reliability is critical and downtime is costly, we always recommend LiFePO4. For budget-conscious residential systems where the client understands the maintenance requirements, quality AGM lead-acid can be a suitable starting point.",
      },
      {
        heading: "Important Installation Considerations",
        body: "Regardless of which technology you choose, these principles apply:",
        bullets: [
          "Never mix old and new batteries, or batteries of different brands and capacities, in the same bank",
          "Ensure your inverter/charger is compatible with your chosen battery chemistry — lithium requires specific charging voltage profiles",
          "Install batteries in a ventilated, shaded location — heat is the enemy of battery life",
          "Size your battery bank for at least 2 days of autonomy to handle cloudy periods",
        ],
      },
    ],
    conclusion: "At Pekims Technologies, we supply and install both battery technologies and will recommend the best fit based on your budget, usage patterns and long-term goals. All our lithium battery systems are supplied with a built-in Battery Management System (BMS) for complete safety and performance monitoring. Contact us to discuss which battery solution is right for your solar system.",
  },

  {
    slug: "solar-system-cost-kenya-2025",
    title: "How Much Does a Solar System Cost in Kenya in 2025?",
    date: "2 May 2025",
    tag: "Pricing",
    readTime: "7 min read",
    img: "https://images.unsplash.com/photo-1761472823286-9f6093ed6663?w=1200&h=600&fit=crop&auto=format",
    excerpt: "We break down the true cost of residential, commercial and agricultural solar systems in Kenya, including installation and maintenance.",
    intro: "One of the most common questions we receive at Pekims Technologies is: 'How much does a solar system cost?' The honest answer is — it depends on your energy needs, the quality of components and the type of system you install. This guide breaks down real price ranges for different system sizes and applications in Kenya in 2025, helping you budget realistically for your solar investment.",
    sections: [
      {
        heading: "Factors That Determine System Cost",
        body: "Before looking at numbers, understand that solar system pricing is driven by several key variables:",
        bullets: [
          "System size (kWp) — directly proportional to cost; doubling capacity roughly doubles the price",
          "Battery type — lithium batteries cost 2–3× more than lead-acid but last much longer",
          "Inverter quality — a premium hybrid inverter with monitoring costs more than a basic off-grid unit",
          "Installation complexity — roof type, cable runs and panel mounting height all affect labour costs",
          "Location — projects outside Nairobi incur transport and accommodation costs for the installation team",
        ],
      },
      {
        heading: "Residential Solar System Costs (2025)",
        body: "Here are typical installed costs for Kenyan homes in 2025. All prices include panels, inverter, batteries, wiring, mounting and professional installation:",
        bullets: [
          "Basic starter system (1 kWp, 200Ah AGM, 1.5 kVA inverter): KES 80,000 – 120,000 — Powers lights, phone charging, small TV and a fan",
          "Small home system (2 kWp, 200Ah lithium, 3 kVA hybrid): KES 180,000 – 260,000 — Adds a medium fridge and laptop",
          "Medium home system (3–5 kWp, 400Ah lithium, 5 kVA hybrid): KES 350,000 – 550,000 — Full home coverage including large fridge, multiple TVs and water pump",
          "Large home system (8–10 kWp, 600Ah lithium, 8–10 kVA hybrid): KES 700,000 – 1,200,000 — High-consumption homes with air conditioning",
        ],
      },
      {
        heading: "Commercial Solar System Costs (2025)",
        body: "Commercial systems benefit from economies of scale. Larger systems have a lower cost per watt:",
        bullets: [
          "Small office / retail shop (5–10 kWp): KES 500,000 – 1,000,000",
          "Medium commercial (20–50 kWp): KES 1.5M – 4.5M",
          "Large commercial / school / hospital (50–100 kWp): KES 4M – 9M",
          "Industrial / manufacturing (100 kWp+): KES 8M – 25M+",
        ],
      },
      {
        heading: "Agricultural Solar System Costs (2025)",
        body: "Agricultural systems are often the highest-ROI solar investments due to the high cost of diesel they replace:",
        bullets: [
          "1 HP solar water pump system: KES 80,000 – 130,000",
          "3 HP solar water pump system: KES 180,000 – 280,000",
          "5 HP solar water pump system: KES 300,000 – 450,000",
          "10 HP solar water pump system: KES 600,000 – 900,000",
          "Solar-powered drip irrigation system (2–5 acres): KES 250,000 – 600,000",
        ],
      },
      {
        heading: "What About After-Sales and Maintenance Costs?",
        body: "A well-installed solar system from Pekims Technologies has very low ongoing costs:",
        bullets: [
          "Panels: no maintenance cost, warranted for 25 years performance",
          "Lithium batteries: no maintenance; replacement expected after 10–15 years",
          "Inverter: minor servicing every 5 years; replacement after 10–15 years",
          "Annual system check by Pekims: KES 5,000 – 15,000 depending on system size",
        ],
      },
      {
        heading: "Financing Options",
        body: "Pekims Technologies works with financial partners to make solar accessible without requiring full upfront payment. Available options include asset finance through commercial banks, SACCO loans, and lease-to-own arrangements. Many clients find that their monthly solar finance repayment is less than their previous monthly electricity bill — meaning the system pays for itself from day one.",
      },
    ],
    conclusion: "The best way to get an accurate cost for your specific situation is to request a free site assessment from Pekims Technologies. Our engineers will assess your energy needs, design the right system and provide a detailed, no-obligation quotation. Contact us today and take the first step towards energy independence.",
  },

  {
    slug: "solar-street-lights-guide",
    title: "Solar Street Lights: Benefits, Types and Installation Guide",
    date: "18 April 2025",
    tag: "Products",
    readTime: "5 min read",
    img: "https://images.unsplash.com/photo-1626006846694-f0852fa032f1?w=1200&h=600&fit=crop&auto=format",
    excerpt: "All-in-one solar street lights are transforming public lighting in Kenya. Here is what you need to know before buying.",
    intro: "Solar street lights have undergone a dramatic transformation over the past decade. Today's all-in-one units integrate the solar panel, battery, LED light and intelligent controller into a single compact fitting that requires no external wiring, no trenching and no electricity bill. From rural roads to urban estates, solar street lights are rapidly replacing grid-connected alternatives across Kenya. This guide explains the key types, performance factors and installation considerations.",
    sections: [
      {
        heading: "Types of Solar Street Lights",
        body: "Three main configurations are available in the Kenyan market:",
        bullets: [
          "All-in-One (AIO) — The solar panel, lithium battery, LED module and controller are all integrated into one unit. Simple to install, modern appearance, no external wiring. Best for most residential and commercial applications.",
          "Split System — The solar panel is mounted separately from the light head, connected by a cable. Allows the panel to be angled optimally for maximum solar harvest. Better for locations with partial shade or specific orientation requirements.",
          "Solar + Battery Box — Panel on pole, battery in a sealed box at the base. Used for very large lights (150W+) where the battery is too heavy to mount in the head unit.",
        ],
      },
      {
        heading: "Key Performance Specifications",
        body: "When comparing solar street lights, focus on these specifications:",
        bullets: [
          "LED Power (Watts) — Determines brightness. 20–40W is suitable for residential paths; 60–100W for main roads; 120–200W for highways and large car parks.",
          "Lumens Output — The actual light output. A good 40W solar LED produces 4,000–5,000 lumens. Beware of cheap lights that overstate wattage.",
          "Battery Capacity (Wh) — Determines how many hours the light runs at full brightness after a full day's charging. Look for at least 2–3 days of autonomy.",
          "Charging Time — A quality unit charges fully in 6–8 hours of good sunlight.",
          "IP Rating — IP65 or higher is essential for weatherproofing in Kenya's rain and humidity.",
          "Working Mode — Good lights offer a motion-sensing mode that dims to 30% when no activity is detected and brightens to 100% when motion is sensed — extending battery life significantly.",
        ],
      },
      {
        heading: "Pole Height and Spacing Guidelines",
        body: "Correct pole placement is as important as the light specification:",
        bullets: [
          "Residential paths and driveways: 4–6m poles, 15–20m spacing",
          "Residential roads: 6–8m poles, 20–30m spacing",
          "Main roads and commercial areas: 8–10m poles, 25–35m spacing",
          "Car parks and security lighting: 8–12m poles, 25–40m spacing",
          "Stagger lights on both sides of wide roads for even illumination",
        ],
      },
      {
        heading: "Installation Requirements",
        body: "All-in-one solar street lights are relatively simple to install, but the following must be done correctly:",
        bullets: [
          "Pole foundation: concrete block sized to wind load specifications for the pole height",
          "Pole orientation: the integrated solar panel must face true north (in Kenya, this means facing north towards the equator) for maximum solar harvest",
          "Tilt angle: the panel should be tilted at approximately 1–5° from horizontal for Kenya's equatorial location",
          "Shade clearance: ensure no trees, buildings or other structures cast shade on the panel during peak sun hours (9 AM – 3 PM)",
        ],
      },
      {
        heading: "Maintenance",
        body: "Solar street lights require very little maintenance but occasional attention ensures long service life:",
        bullets: [
          "Clean the solar panel surface every 3 months to remove dust (major cause of reduced output)",
          "Inspect and tighten pole base bolts annually",
          "Check LED lens for cracks or moisture ingress annually",
          "Battery replacement expected after 5–8 years depending on the technology used",
        ],
      },
    ],
    conclusion: "Pekims Technologies has supplied and installed over 500 solar street lights across Kenya — from private estate roads to public infrastructure projects. We supply all-in-one units from 20W to 200W with working modes tailored to each application. Contact our team for a site survey and lighting design plan.",
  },

  {
    slug: "solar-installation-mistakes",
    title: "Top 5 Mistakes to Avoid When Installing a Solar System",
    date: "5 April 2025",
    tag: "Installation",
    readTime: "6 min read",
    img: "https://images.unsplash.com/photo-1668097613572-40b7c11c8727?w=1200&h=600&fit=crop&auto=format",
    excerpt: "Avoid costly errors with this practical checklist from our experienced solar engineers at Pekims Technologies.",
    intro: "As solar installations have grown rapidly across Kenya, so has the number of poorly designed and badly installed systems. At Pekims Technologies, our engineers are frequently called to assess and repair systems installed by inexperienced contractors. Many of these problems could have been easily avoided with the right knowledge upfront. Here are the five most common mistakes we see — and exactly how to avoid them.",
    sections: [
      {
        heading: "Mistake 1: Undersizing the Battery Bank",
        body: "The most common mistake in residential solar installations is using too small a battery bank. Many installers size the battery based only on nighttime load, ignoring cloudy-day autonomy. In Nairobi, cloud cover during the long rains (March–May) and short rains (October–December) can reduce solar generation by 60–70% for several consecutive days. A battery bank sized for only one night will leave you with no power by mid-afternoon on a cloudy day. The correct approach is to size for at least 2–3 days of full autonomy without solar input.",
        bullets: [
          "Always calculate your daily energy consumption in kWh before selecting a battery",
          "Size for a minimum of 2 days autonomy, ideally 3 for critical loads",
          "Account for battery depth of discharge — only 50% for lead-acid, 80% for lithium",
          "Factor in inverter efficiency losses (typically 5–8%) when sizing",
        ],
      },
      {
        heading: "Mistake 2: Using Undersized Cable",
        body: "Undersized DC wiring between panels, batteries and inverter is one of the most dangerous installation errors. Thin cables have high resistance, which causes voltage drop (reduced system efficiency) and heat buildup (fire risk). DC wiring in solar systems carries high currents — a 5 kW inverter at 48V draws over 100 amps. Many cheap installers use 6mm² cable where 16mm² or even 25mm² is required.",
        bullets: [
          "Always use a cable sizing calculator based on current, voltage and cable run length",
          "DC cable runs should be as short as possible — place inverter close to battery bank",
          "Use tinned copper cable rated for DC solar applications",
          "All connections must be made with correct MC4 connectors and proper crimping tools — never bare wire twisted together",
        ],
      },
      {
        heading: "Mistake 3: Installing Panels Without Shade Analysis",
        body: "A single shaded panel in a string can reduce the output of all panels in that string by up to 80%. This phenomenon, known as the Christmas light effect, is responsible for massive energy losses in poorly sited systems. Trees, water tanks, chimneys, satellite dishes and neighbouring buildings can all cast shade that wasn't apparent during a quick site visit. A proper shade analysis must be conducted at different times of day and across different seasons.",
        bullets: [
          "Use a solar pathfinder or SunEye tool to map shading throughout the day",
          "Consider shade-tolerant wiring configurations using optimisers or microinverters if shading is unavoidable",
          "Plan for tree growth — a tree that doesn't shade panels today may do so in 5 years",
          "Trim or remove shading vegetation before installation where possible",
        ],
      },
      {
        heading: "Mistake 4: Incorrect Inverter/Battery Matching",
        body: "Modern lithium batteries require a specific charging voltage profile that is different from lead-acid batteries. A standard inverter configured for lead-acid will undercharge or damage lithium batteries if not properly reprogrammed. We frequently encounter lithium batteries connected to inverters that have never had their settings updated from the factory default lead-acid profile — resulting in premature battery failure and voided warranties.",
        bullets: [
          "Always confirm your inverter explicitly supports your chosen battery chemistry before purchase",
          "Programme the correct charging voltage, float voltage and charge current limits for your specific battery",
          "Obtain written confirmation from your installer that settings have been configured correctly",
          "Register your battery's BMS with the inverter's monitoring system where applicable",
        ],
      },
      {
        heading: "Mistake 5: No Earthing or Lightning Protection",
        body: "Kenya has one of the highest lightning strike rates in Africa, particularly in areas around Lake Victoria, Mount Kenya and the Rift Valley highlands. Solar panels mounted on a roof significantly increase the risk of a lightning strike damaging the entire electrical system. Yet the majority of solar systems installed in Kenya have no proper earthing or surge protection. A direct or nearby lightning strike can destroy panels, inverter, batteries and all connected appliances in seconds.",
        bullets: [
          "Install a proper earth rod and bond all metallic components of the solar system to it",
          "Fit DC surge protection devices (SPDs) at both the panel array and the inverter input",
          "Fit AC surge protection at the inverter output and main distribution board",
          "Consider a lightning rod installation for buildings in high-lightning-risk areas",
        ],
      },
    ],
    conclusion: "Every one of these mistakes is completely preventable with the right expertise and quality components. At Pekims Technologies, all our installations follow a comprehensive quality checklist developed over hundreds of projects across Kenya. Our systems come with a full workmanship warranty, and we perform a commissioning test on every installation before handover. If you have an existing solar system that is underperforming, contact us for a professional system audit.",
  },
];
